name: Terraform-Destroy-Lab

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_WORKING_DIR: terraform

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: destroy-approval
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -var="notification_email=${{ secrets.BUDGET_EMAIL }}"
